---
- hosts: db
  tasks:
    - name: Install mysql
      become: yes
      apt:
        name: mysql-server
        update_cache: yes

    - name: Replace a bind-address
      become: yes
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '127.0.0.1'
        replace: "0.0.0.0"
    - name: Restart mysql service
      become: yes
      service:
        name: mysql
        state: restarted
    - name: Create database user
      become: yes 
      mysql_user:
        name: fbird
        password: fbird
        host: "%"
        priv: 'fbird.*:ALL'
        state: present
    - name: Create a new database with name 'fbird'
      become: yes
      mysql_db:
        name: fbird
        state: present
    - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
      become: yes
      mysql_db:
        state: import
        name: all
        target: /home/vagrant/dump.sql

- hosts: app
  become: yes
  tasks:
    - name: install JDK 11
      apt:
        name: openjdk-11-jdk
        state: present
    - name: add tomcat group
      group:
        name: tomcat

    - name: add tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /user/share/tomcat
        createhome: no

    - name: create /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755

    - name: download & unarchive
      unarchive:
        src: http://apache.cp.if.ua/tomcat/tomcat-9/v9.0.29/bin/apache-tomcat-9.0.29.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]
    
    - name: Copy Tomcat context.xml
      copy:
         src: /home/vagrant/context.xml
         dest: /opt/tomcat/webapps/manager/META-INF/context.xml
         mode: 0755

    - name: Copy Tomcat tomcat-users
      copy:
         src: /home/vagrant/tomcat-users.xml
         dest: /opt/tomcat/conf/tomcat-users.xml
         mode: 0755

    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      copy:
         src: /home/vagrant/tomcat2.service
         dest: /etc/systemd/system/tomcat.service
         mode: 0755

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: true

    - name: deploy app
      copy:
         src: /home/vagrant/fbird.war
         dest: /opt/tomcat/webapps/fbird.war
         mode: 0755

- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: install JDK 8
      apt:
        name: openjdk-8-jdk
        state: present
    - name: install maven
      apt:
        name: maven
        state: present
    - name: Add Jenkins apt repository key.
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
    - name: Add Jenkins apt repository.
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present
        update_cache: true
    - name: install jenkins
      apt:
        name: jenkins
        state: present
    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: "Initial password already set"
      register: result

    - name: Print init password Jenkins
      debug:
        var: result.stdout


